/* Creating new Virtual Warehouses and Assigning them to Different Roles */
-- Log in as Sysadmin Yometh
use role sysadmin;
show warehouses;
/* Virtual Warehouse - Common Activities */
CREATE or replace WAREHOUSE COMMON_WH WITH 
WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

/* Virtual Warehouse - Sales */
CREATE or replace WAREHOUSE SALES_WH WITH 
WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

/* Virtual Warehouse - Customer Support */
CREATE or replace WAREHOUSE CUSTOMER_SUPPORT_WH WITH 
WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

/* Virtual Warehouse - Data Science */
CREATE or replace WAREHOUSE DATASCIENCE_WH WITH 
WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

/* Virtual Warehouse - Marketting */
CREATE or replace WAREHOUSE MARKETTING_WH WITH 
WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

-- Assigning Virtual Warehouses to different Roles in Different Divisions
GRANT USAGE ON WAREHOUSE COMMON_WH TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE SALES_WH TO ROLE SALES_ANALYST;
GRANT USAGE ON WAREHOUSE SALES_WH TO ROLE SALES_DBA;
GRANT USAGE ON WAREHOUSE CUSTOMER_SUPPORT_WH TO ROLE CUSTOMER_SUPPORT_ANALYST;
GRANT USAGE ON WAREHOUSE CUSTOMER_SUPPORT_WH TO ROLE CUSTOMER_SUPPORT_DBA;
GRANT USAGE ON WAREHOUSE DATASCIENCE_WH TO ROLE DATASCIENTIST;
GRANT USAGE ON WAREHOUSE MARKETTING_WH TO ROLE MARKETTING_ANALYST;
GRANT USAGE ON WAREHOUSE MARKETTING_WH TO ROLE MARKETTING_DBA;


