-- We are now going to create the VWHs and databases and assigne them to different departments
-- let's create a new small size virtual warehouse
CREATE WAREHOUSE COMMON_WH WITH 
WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

-- GRANT IT TO PUBLIC ROLE SO ANYONE CAN MAKE USE OF IT
GRANT USAGE ON WAREHOUSE COMMON_WH TO ROLE PUBLIC;

-- LET'S CREATE A NEW TEMPORARY DATABASE FOR STORING TEMPORARY DATA AND GRANT IT TO PUBLIC ROLE
CREATE DATABASE TEMP_DATABASE;
GRANT USAGE ON DATABASE TEMP_DATABASE TO ROLE PUBLIC;

-- CREATE A DATABASE WHERE WE WILL HAVE ALL THE MARKETING TABLES
-- GRANT ACCESS TO THIS DATABASE FOR MARKETING_DBA
CREATE DATABASE MARKETING_DATABASE;
GRANT OWNERSHIP ON SCHEMA MARKETING_DATABASE.PUBLIC TO ROLE MARKETING_DBA;
GRANT OWNERSHIP ON DATABASE MARKETING_DATABASE TO ROLE MARKETING_DBA;

-- create a database where we will have all the finance tables 
-- grant access to this database for finance_dba
CREATE DATABASE FINANCE_DATABASE;
GRANT OWNERSHIP ON SCHEMA FINANCE_DATABASE.PUBLIC TO ROLE FINANCE_DBA;
GRANT OWNERSHIP ON DATABASE FINANCE_DATABASE TO ROLE FINANCE_DBA;




